
import "./globals.css";
import { Providers } from "@/components/providers"
import {AppSidebar} from "@/components/layout/app-sidebar";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar"
import { ModeToggle } from "@/components/mode-toggle";
import { DM_Sans, Lora, IBM_Plex_Mono } from "next/font/google";
const fontSans = DM_Sans({
  subsets: ["latin"],
  variable: "--font-sans",
  weight: ["400", "500", "700"],
});

const fontSerif = Lora({
  subsets: ["latin"],
  variable: "--font-serif",
  weight: ["400", "600", "700"],
});

const fontMono = IBM_Plex_Mono({
  subsets: ["latin"],
  variable: "--font-mono",
  weight: ["400", "500", "700"], // ✅ REQUIRED
});
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning >
      <body className={`${fontSans.variable} ${fontSerif.variable} ${fontMono.variable} antialiased`}>
        
        <Providers>
        <SidebarProvider >
          <AppSidebar />
          <main className="w-[100%]  h-screen">
            <div className="flex flex-row justify-between items-center p-4">
              <SidebarTrigger />
            <ModeToggle/>
            </div>
            
            {children}
            
          </main>
        </SidebarProvider>
        </Providers>
      </body>
    </html>
  );
}
